spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/tickets
    username: sa
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: false
      use_sql_comments: false
      format_sql: false

